### ISSUE TITLE
Russian cyrillic characters not being handled correctly

### ISSUE THREAD

**Issue by sideloading** [w0d4/yt-backup#14]
Same issue to #12, except the channel name is in Cyrillic.

youtube-dl is also able to handle these characters correctly.

```
2020-05-18 13:35:58,147 - yt-backup - INFO - Video 1IbvteArd0o - Асмр қазақша ролевая игра бет күтімі/ асмр по казахскому ролевая игра is not yet downloaded. Downloading now.
Traceback (most recent call last):
  File "yt-backup.py", line 1154, in <module>
    download_videos()
  File "yt-backup.py", line 713, in download_videos
    video.runtime = get_video_duration(video_file)
  File "yt-backup.py", line 851, in get_video_duration
    return float(result.stdout)
ValueError: could not convert string to float: b'/mnt/shares/yt-backup/tmp//\xd0\x91\xd0\xb0\xd0\xbb\xd0\xb0\xd0\xbf\xd0\xb0\xd0\xbd\xd0\xba\xd0\xb0 Asmr [UC3wJ0inRG4zrFZUyDnqNVrA]/20200518 \xd0\x90\xd1\x81\xd0\xbc\xd1\x80 \xd2\x9b\xd0\xb0\xd0\xb7\xd0\xb0\xd2\x9b\xd1\x88\xd0\xb0 \xd1\x80\xd0\xbe\xd0\xbb\xd0\xb5\xd0\xb2\xd0\xb0\xd1\x8f \xd0\xb8\xd0\xb3\xd1\x80\xd0\xb0 \xd0\xb1\xd0\xb5\xd1\x82 \xd0\xba\xd2\xaf\xd1\x82\xd1\x96\xd0\xbc\xd1\x96_ \xd0\xb0\xd1\x81\xd0\xbc\xd1\x80 \xd0\xbf\xd0\xbe \xd0\xba\xd0\xb0\xd0\xb7\xd0\xb0\xd1\x85\xd1\x81\xd0\xba\xd0\xbe\xd0\xbc\xd1\x83 \xd1\x80\xd0\xbe\xd0\xbb\xd0\xb5\xd0\xb2\xd0\xb0\xd1\x8f \xd0\xb8\xd0\xb3\xd1\x80\xd0\xb0 1080p 1IbvteArd0o.f137.mp4: No such file or directory\n'
```

Seems to be a character encoding issue

**Comment by sideloading** [comment]
I'm not even sure what happened, I re-ran `python3 yt-backup.py download_videos` and it seems to have downloaded correctly. Will reopen if I come across it again.
