### ISSUE TITLE
Traceback error: MySQL server has gone away

### ISSUE THREAD

**Issue by sideloading** [w0d4/yt-backup#23]
**Describe the bug**
Not exactly sure what's happening here, just letting videos download but then I got a traceback error with the exception 'MySQL server has gone away'. Logs below.

**To Reproduce**
Steps to reproduce the behavior: I ran the main `run` function, and let the queue download. One video took about ~30 minutes to complete until I got the Traceback error.

**Expected behavior**
Able to re-connect/re-try if errors pushing to DB.

**Debug log**
```
2020-05-21 19:40:22,365 - yt-backup - DEBUG - Video runtime was set to 741.481 seconds
2020-05-21 19:40:22,429 - yt-backup - DEBUG - Video resolution was set to 1920x1080
2020-05-21 19:40:22,429 - yt-backup - DEBUG - Video size was set to 407981720 bytes
Traceback (most recent call last):
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (2006, 'MySQL server has gone away')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yt-backup.py", line 1576, in <module>
    download_videos()
  File "yt-backup.py", line 976, in download_videos
    session.commit()
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1036, in commit
    self.transaction.commit()
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 503, in commit
    self._prepare_impl()
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 482, in _prepare_impl
    self.session.flush()
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2496, in flush
    self._flush(objects)
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2637, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2597, in _flush
    flush_context.execute()
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 236, in save_obj
    update,
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 995, in _emit_update_statements
    statement, multiparams
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 984, in execute
    return meth(self, multiparams, params)
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1103, in _execute_clauseelement
    distilled_params,
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1288, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1482, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (2006, 'MySQL server has gone away')
[SQL: UPDATE videos SET size=%s, resolution=%s, runtime=%s, downloaded=%s WHERE videos.id = %s]
[parameters: (407981720, '1920x1080', 741.481, '2020-05-21 11:40:22', 11431)]
(Background on this error at: http://sqlalche.me/e/e3q8)
```

**Additional context**
Re-running yt-backyup.py and it downloads fine, so not a consistent error.

**Comment by w0d4** [comment]
Interesting. Have never seen that until now.
I will research how this could happen and what to do against.

**Comment by w0d4** [comment]
Please update. I added some mitigation. See f25a7c560cff5e8e5095022c4bf6d5a1f86cfa68

**Comment by sideloading** [comment]
Thanks, will re-open if I have the issue again 👍

**Comment by sideloading** [comment]
Unfortunately I've gotten this error once again :(

```
Traceback (most recent call last):
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (2006, 'MySQL server has gone away')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yt-backup.py", line 1595, in <module>
    download_videos()
  File "yt-backup.py", line 994, in download_videos
    session.commit()
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1036, in commit
    self.transaction.commit()
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 503, in commit
    self._prepare_impl()
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 482, in _prepare_impl
    self.session.flush()
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2496, in flush
    self._flush(objects)
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2637, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2597, in _flush
    flush_context.execute()
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 236, in save_obj
    update,
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 995, in _emit_update_statements
    statement, multiparams
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 984, in execute
    return meth(self, multiparams, params)
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1103, in _execute_clauseelement
    distilled_params,
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1288, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1482, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (2006, 'MySQL server has gone away')
[SQL: UPDATE videos SET size=%s, resolution=%s, runtime=%s, downloaded=%s WHERE videos.id = %s]
[parameters: (551443543, '1920x1080', 985.687, '2020-05-22 12:11:06', 11541)]
(Background on this error at: http://sqlalche.me/e/e3q8)
```

Perhaps this error can be caught, and then re-try the download function, as for the moment I must delete the lockfile, and re-run it.

**Comment by w0d4** [comment]
I will try to build a catch for this error.
You could try increasing your MySQL timeout settings: https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_wait_timeout

**Comment by sideloading** [comment]
>You could try increasing your MySQL timeout settings

Thanks for pointing this out. I checked my MariaDB and it was set to 600s/10min, which makes sense for the crash. I've increased it to 3600(1hr), is your config on the default value of 28800(8h)?

**Comment by w0d4** [comment]
Yes, my config is on the default value of 28800 out of the box with ubuntu 19.04.

**Comment by sideloading** [comment]
I will close this as I haven't gotten this error anymore. Thanks
