### ISSUE TITLE
Traceback error when adding a channel that already exists

### ISSUE THREAD

**Issue by sideloading** [w0d4/yt-backup#24]
**Describe the bug**
When adding a channel ID that is already added to yt-backup, a Traceback error occurs.

**To Reproduce**
Steps to reproduce the behavior: Add pre-existing channel with `python3 yt-backup.py add_channel --channel_id <youtube-channel-id>`

**Expected behavior**
Catch the error.

**Debug log**
```
$ python3 yt-backup.py add_channel --channel_id <youtube-channel-id>
2020-05-21 20:35:30,316 - yt-backup - INFO - Channel is already in database
2020-05-21 20:35:30,325 - yt-backup - INFO - Adding default playlist uploads to the channel.
Traceback (most recent call last):
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1048, "Column 'channel_id' cannot be null")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yt-backup.py", line 1559, in <module>
    add_channel(channel_id)
  File "yt-backup.py", line 508, in add_channel
    add_uploads_playlist(channel)
  File "yt-backup.py", line 524, in add_uploads_playlist
    session.commit()
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1036, in commit
    self.transaction.commit()
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 503, in commit
    self._prepare_impl()
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 482, in _prepare_impl
    self.session.flush()
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2496, in flush
    self._flush(objects)
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2637, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2597, in _flush
    flush_context.execute()
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    insert,
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 1136, in _emit_insert_statements
    statement, params
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 984, in execute
    return meth(self, multiparams, params)
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1103, in _execute_clauseelement
    distilled_params,
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1288, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1482, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (1048, "Column 'channel_id' cannot be null")
[SQL: INSERT INTO playlists (playlist_id, playlist_name, entries, monitored, channel_id, download_from_date, etag) VALUES (%s, %s, %s, %s, %s, %s, %s)]
[parameters: ('UUvjvAUTkbjsd6UxU_7sOncQ', 'uploads', None, 1, None, None, None)]
(Background on this error at: http://sqlalche.me/e/e3q8)

```

**Additional context**
n/a

**Comment by w0d4** [comment]
Fixed. d6935b283acc7314c34ffb74c40da9412b463bcd
