### ISSUE TITLE
Traceback error: Directory not empty

### ISSUE THREAD

**Issue by sideloading** [w0d4/yt-backup#26]
**Describe the bug**
I receive a traceback error when the tmp folder directory was in use, therefore unable to delete the file/folders, or start the download_videos process

**To Reproduce**
Steps to reproduce the behavior: Not recommended but browse to tmp directory through SMB

**Expected behavior**
Catch the error and quit nicely

**Debug log**
```
Traceback (most recent call last):
  File "yt-backup.py", line 1595, in <module>
    download_videos()
  File "yt-backup.py", line 871, in download_videos
    shutil.rmtree(config["base"]["download_dir"])
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/shutil.py", line 484, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/shutil.py", line 482, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/mnt/shares/yt-backup/tmp'
```

**Additional context**

**Comment by w0d4** [comment]
This should be fixed in 8cd6617
