### ISSUE TITLE
Traceback error on geoblocked video

### ISSUE THREAD

**Issue by sideloading** [w0d4/yt-backup#29]
**Describe the bug**
I have received a Traceback for a geoblocked video, which isn't handled and crashes the script. 

**To Reproduce**
Please share at least the video ID and your naming-format option.

**Expected behavior**
Mark the video as Geo-blocked and continue to the rest of the queue. 

**Debug log**
If applicable, add debug log of your problem with --debug
```
2020-05-23 07:38:51,825 - yt-backup - INFO - Video SSE_tHRE5Vc - PLAYLIST ALEATÓRIA is not yet downloaded. Downloading now.
2020-05-23 07:38:51,839 - yt-backup - DEBUG - Video belongs to playlist 272
2020-05-23 07:38:51,845 - yt-backup - DEBUG - Video belongs to channel Giovanna Akemi [UCdy7eS9IW78yamiuRHhNwWw]
2020-05-23 07:38:52,028 - yt-backup - DEBUG - Escaped Channel name is Giovanna Akemi \[UCdy7eS9IW78yamiuRHhNwWw\]
2020-05-23 07:38:52,028 - yt-backup - DEBUG - youtube-dl command is: /usr/local/bin/youtube-dl --continue  -4 --download-archive /home/user/yt-backup/archive.list --output /tmp/youtube-dl/"Giovanna Akemi [UCdy7eS9IW78yamiuRHhNwWw]"/"%(upload_date)s %(title).100s %(height)sp %(id)s.%(ext)s" --ignore-config --ignore-errors --merge-output-format mkv  --no-overwrites --format "(bestvideo+bestaudio/best)" --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36" --write-info-json --add-metadata --write-thumbnail --prefer-ffmpeg --merge-output-format mkv --no-overwrites https://youtu.be/SSE_tHRE5Vc
2020-05-23 07:38:59,225 - yt-backup - DEBUG - b'[youtube] SSE_tHRE5Vc: Downloading webpage\n'
2020-05-23 07:38:59,226 - yt-backup - DEBUG - b'ERROR: SSE_tHRE5Vc: YouTube said: This video contains content from Voodoo_Music, who has blocked it in your country on copyright grounds.\nSorry about that.\n'
2020-05-23 07:38:59,226 - yt-backup - ERROR - This video is blocked in your country due to copyright reasons.
2020-05-23 07:38:59,226 - yt-backup - INFO - This video is geoblocked on current country FR. Will get complete geoblock list.
2020-05-23 07:38:59,535 - yt-backup - DEBUG - Excuting youtube API call for getting channel id by video_id
2020-05-23 07:38:59,743 - yt-backup - DEBUG - {'kind': 'youtube#videoListResponse', 'etag': 'IV593z2rcN4Q-ccJwhmbRU-x7Vw', 'items': [{'kind': 'youtube#video', 'etag': 'LIbb_KsqsXmDmGopRFsyVDRqjig', 'id': 'SSE_tHRE5Vc', 'contentDetails': {'duration': 'PT9M43S', 'dimension': '2d', 'definition': 'hd', 'caption': 'false', 'licensedContent': False, 'regionRestriction': {'allowed': ['VA', 'NZ', 'AU', 'IT', 'SM']}, 'contentRating': {}, 'projection': 'rectangular'}}], 'pageInfo': {'totalResults': 1, 'resultsPerPage': 1}}
Traceback (most recent call last):
  File "yt-backup.py", line 1590, in <module>
    download_videos()
  File "yt-backup.py", line 933, in download_videos
    video_geoblock_list = get_geoblock_list_for_one_video(video.video_id)
  File "yt-backup.py", line 573, in get_geoblock_list_for_one_video
    for entry in response["items"][0]["contentDetails"]["regionRestriction"]["blocked"]:
KeyError: 'blocked'
```

**Additional context**

**Comment by w0d4** [comment]
Maybe youtube api changed. I would expect blocked part in the answer which contains the country codes. Here I see an allowed block.

**Comment by w0d4** [comment]
Docu of youtube API says, both could be there, but only one must be there...
I will try to implement this...

**Comment by w0d4** [comment]
There is a workaround for this in the latest release. A real fix will follow.

**Comment by sideloading** [comment]
Thank you, the script is able to complete the run now 😃
