### ISSUE TITLE
Traceback JSONDecodeError, script not longer works

### ISSUE THREAD

**Issue by sideloading** [w0d4/yt-backup#30]
**Describe the bug**
When attempting to run `yt-backup.py` I get a JSONDecodeError which crashes the script. 

**To Reproduce**
Unfortunately it seems to have happened out of nowhere, but running any function crashes. 
I've tried deleting client_secret.json (along with the token.pickle, and hidden files), re-downloaded my secret and still the issue appears.

**Expected behavior**
Read JSON files correctly, and run the script.

**Debug log**
```bash
$ python3 yt-backup.py
Traceback (most recent call last):
  File "yt-backup.py", line 41, in <module>
    from base import Session, engine, Base
  File "/mnt/shares/yt-backup/base.py", line 25, in <module>
    config = json.load(f)
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/yt/.pyenv/versions/3.6.6/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 23 column 194 (char 1002)
```

**Additional context**
Perhaps a solution here: https://stackoverflow.com/questions/9156417/valid-json-giving-jsondecodeerror-expecting-delimiter

**Comment by sideloading** [comment]
Issue was with my `config.json`, I had extra commas..
